/**
 * Notification bell + dropdown.
 *
 * Content and read-state logic moved verbatim from the original Layout.tsx
 * (static per-role notifications + AppContext security alerts, `readNotifs`
 * / `markAllRead` / `markOneRead`). Only the presentation is restyled —
 * the dropdown now uses the current role accent instead of the hardcoded
 * emerald. The real `/api/notifications` API is intentionally NOT wired
 * (that would be a behavior change, out of scope).
 */
import React, { useEffect, useRef, useState } from 'react';
import { Bell } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { useRoleAccent } from '../../utils/roleTheme';

const ALL_NOTIFICATIONS: Record<
  string,
  { id: number; icon: string; text: string; time: string }[]
> = {
  admin: [
    {
      id: 1,
      icon: '👤',
      text: 'New user account created: teacher03 (Teacher)',
      time: 'Today 10:02'
    },
    {
      id: 2,
      icon: '🔄',
      text: 'Bulk promotion submitted by Mr. Ramon Dela Cruz — 7-Star (42 students)',
      time: 'Today 09:45'
    },
    {
      id: 3,
      icon: '💾',
      text: 'Database backup completed successfully.',
      time: 'Today 08:00'
    },
    {
      id: 4,
      icon: '📅',
      text: 'Enrollment period is currently OPEN for SY 2025–2026.',
      time: 'Yesterday'
    },
    {
      id: 5,
      icon: '🤖',
      text: 'AI At-Risk model run completed — 11 students flagged system-wide.',
      time: 'Yesterday'
    }
  ],
  teacher: [
    {
      id: 1,
      icon: '✅',
      text: 'Grades successfully locked: 7-Star — Mathematics.',
      time: 'Today 10:30'
    },
    {
      id: 2,
      icon: '🔴',
      text: 'At-Risk alert: Juan dela Cruz (7-Gold) — declining grade trajectory detected.',
      time: 'Today 09:00'
    },
    {
      id: 3,
      icon: '🟡',
      text: 'Needs Monitoring: Ana Reyes (8-Silver) — Q3 average dropped below 82.',
      time: 'Today 08:45'
    },
    {
      id: 4,
      icon: '👨‍🎓',
      text: 'New student enrolled in your section: Mark Bautista — 7-Gold.',
      time: 'Yesterday'
    },
    {
      id: 5,
      icon: '📅',
      text: 'Enrollment period is open. You may now enroll new and returning students.',
      time: 'Yesterday'
    }
  ],
  registrar: [
    {
      id: 1,
      icon: '📋',
      text: 'Teacher Mr. Dela Cruz submitted grades for 7-Star — ready for SF generation.',
      time: 'Today 10:30'
    },
    {
      id: 2,
      icon: '📤',
      text: 'SF1 generated successfully for Grade 7-Star — SY 2025–2026.',
      time: 'Today 09:12'
    },
    {
      id: 3,
      icon: '🔼',
      text: 'Bulk promotion record received: 7-Star → Grade 8 (42 students). Record PR-003.',
      time: 'Today 09:45'
    },
    {
      id: 4,
      icon: '🤖',
      text: 'At-Risk report updated — 2 At-Risk, 4 Needs Monitoring across all sections.',
      time: 'Yesterday'
    },
    {
      id: 5,
      icon: '👤',
      text: 'Student record updated: Maria Santos — SF10 generated by registrar01.',
      time: 'Yesterday'
    }
  ],
  principal: [
    {
      id: 1,
      icon: '📊',
      text: 'School-wide enrollment: 1,247 students enrolled for SY 2025–2026.',
      time: 'Today 10:30'
    },
    {
      id: 2,
      icon: '📝',
      text: 'Grade submission progress: 14/24 sections have submitted Q4 grades.',
      time: 'Today 09:45'
    },
    {
      id: 3,
      icon: '⚠️',
      text: 'At-Risk report: 6 students flagged across Grade 7–10 sections.',
      time: 'Today 08:30'
    },
    {
      id: 4,
      icon: '🎓',
      text: 'Promotion status: 92% of students promoted, 8% retained this school year.',
      time: 'Yesterday'
    },
    {
      id: 5,
      icon: '👥',
      text: 'Section population report generated — 24 sections across 6 grade levels.',
      time: 'Yesterday'
    }
  ]
};

export function NotificationsDropdown() {
  const {
    role,
    readNotifs,
    markAllRead,
    markOneRead,
    securityNotifs
  } = useApp();
  const accent = useRoleAccent();
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  const staticNotifs = ALL_NOTIFICATIONS[role || 'admin'] || [];
  const currentNotifs = [
    ...securityNotifs.map(n => ({
      id: parseInt(n.id, 36) || 9999,
      icon: n.icon,
      text: n.text,
      time: n.time,
      isSecurity: true
    })),
    ...staticNotifs.map(n => ({ ...n, isSecurity: false }))
  ];
  const unreadCount =
    securityNotifs.length +
    staticNotifs.filter(n => !readNotifs.includes(n.id)).length;

  // Close when clicking outside the bell / panel.
  useEffect(() => {
    const handleClick = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node))
        setOpen(false);
    };
    if (open) document.addEventListener('mousedown', handleClick);
    return () => document.removeEventListener('mousedown', handleClick);
  }, [open]);

  return (
    <div className="relative" ref={ref}>
      <button
        onClick={() => setOpen(o => !o)}
        aria-label={
          unreadCount > 0
            ? `Notifications, ${unreadCount} unread`
            : 'Notifications'
        }
        aria-expanded={open}
        aria-haspopup="true"
        className="relative inline-flex h-11 w-11 items-center justify-center rounded-xl text-gray-500 transition-colors hover:bg-gray-100 hover:text-gray-700 lg:h-10 lg:w-10 dark:text-slate-400 dark:hover:bg-slate-800 dark:hover:text-slate-200">
        <Bell size={20} />
        {unreadCount > 0 && (
          <span
            className="absolute right-1.5 top-1.5 flex h-4 min-w-4 items-center justify-center rounded-full px-1 text-[10px] font-bold leading-none text-white ring-2 ring-white dark:ring-slate-900"
            style={{ backgroundColor: accent.chartHex }}>
            {unreadCount > 9 ? '9+' : unreadCount}
          </span>
        )}
      </button>

      {open && (
        <div className="animate-scale-in absolute right-0 top-12 z-50 w-[min(92vw,360px)] overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-2xl dark:border-slate-700 dark:bg-slate-800">
          {/* Header */}
          <div className="flex items-center justify-between border-b border-gray-100 px-4 py-3 dark:border-slate-700">
            <div className="flex items-center gap-2">
              <span
                className="h-2 w-2 animate-pulse rounded-full"
                style={{ backgroundColor: accent.chartHex }}
              />
              <p className="text-sm font-semibold text-gray-800 dark:text-slate-100">
                Notifications
              </p>
            </div>
            <div className="flex items-center gap-2">
              {unreadCount > 0 && (
                <span
                  className="rounded-full px-2 py-0.5 text-[11px] font-semibold"
                  style={{
                    backgroundColor: `${accent.chartHex}1a`,
                    color: accent.chartHex
                  }}>
                  {unreadCount} new
                </span>
              )}
              <button
                onClick={markAllRead}
                className="text-xs font-medium transition-colors hover:underline"
                style={{ color: accent.chartHex }}>
                Mark all read
              </button>
            </div>
          </div>

          {/* Items */}
          <div className="app-scroll max-h-72 overflow-y-auto">
            {currentNotifs.map((n, idx) => {
              const isUnread = !readNotifs.includes(n.id);
              const isSec = (n as { isSecurity?: boolean }).isSecurity;
              return (
                <div
                  key={`${n.id}-${idx}`}
                  onClick={() => !isSec && markOneRead(n.id)}
                  className={`flex cursor-pointer items-start gap-3 px-4 py-3 transition-colors hover:bg-gray-50 dark:hover:bg-slate-700/40 ${
                    idx > 0
                      ? 'border-t border-gray-100 dark:border-slate-700/60'
                      : ''
                  }`}
                  style={{
                    backgroundColor: isSec
                      ? 'rgba(239,68,68,0.08)'
                      : isUnread
                        ? `${accent.chartHex}0d`
                        : 'transparent'
                  }}>
                  <span className="mt-0.5 flex-shrink-0 text-base">{n.icon}</span>
                  <div className="min-w-0 flex-1">
                    {isSec && (
                      <p className="mb-0.5 text-[11px] font-bold uppercase tracking-wide text-red-500">
                        Security Alert
                      </p>
                    )}
                    <p className="text-xs leading-snug text-gray-700 dark:text-slate-200">
                      {n.text}
                    </p>
                    <p className="mt-0.5 text-[11px] text-gray-400 dark:text-slate-500">
                      {n.time}
                    </p>
                  </div>
                  {(isSec || isUnread) && (
                    <span
                      className="mt-1.5 h-2 w-2 flex-shrink-0 rounded-full"
                      style={{
                        backgroundColor: isSec ? '#f87171' : accent.chartHex
                      }}
                    />
                  )}
                </div>
              );
            })}
          </div>

          {/* Footer */}
          <div className="border-t border-gray-100 px-4 py-2.5 text-center dark:border-slate-700">
            <p className="text-[11px] text-gray-400 dark:text-slate-500">
              Hi5 Portal · Notification Center
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
